name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation com cores personalizadas
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: DudaCeleste  # Substitua pelo seu usuário
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/snake-animation.gif
          color_snake: "#FFB6DE"              # Cor rosa para a cobrinha
          color_dots: "#E5A3C7,#D18FB8"       # Cores dos pontos (gradiente)

      # Envia para o branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
